#
# @Cache-Control: 
# @infer true
# @view 
#
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX np: <http://www.nanopub.org/nschema#>
PREFIX nano: <http://example.com/nanoSchema/>

SELECT ?user ?label {
    <$nanopub> a np:Nanopublication
        ; nano:downVotedBy ?user .

    ?user rdfs:label ?label .
}
