#
# @Cache-Control: 
# @infer true
# @view 
#
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX oa: <http://www.w3.org/ns/oa#>

SELECT ?link ?label ?motivation ?creator ?timestamp {
    ?link a oa:Annotation
        ; rdfs:label ?label
        ; oa:motivatedBy ?motivation
        ; prov:wasGeneratedBy ?prov .

    ?prov prov:wasAssociatedWith ?user 
        ; prov:startedAtTime ?timestamp .
    ?user rdfs:label ?creator .
}
